---
title: "Chicago Weather"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(httr)
library(jsonlite)
library(lubridate)
```

```{r get data}
# maybe now??
lpz_loc = c(41.921, -87.634)
metadata_binary = GET(paste0("https://api.weather.gov/points/", lpz_loc[1], ",", lpz_loc[2]))
metadata_json = jsonlite::fromJSON(content(metadata_binary, as="text"))
daily_url = metadata_json$properties$forecast
hourly_url = metadata_json$properties$forecastHourly

daily_forecast = jsonlite::fromJSON(content(GET(daily_url), as="text"))$properties$periods
hourly_forecast = jsonlite::fromJSON(content(GET(hourly_url), as="text"))$properties$periods
hourly_forecast$startTime = as.POSIXct(substr(hourly_forecast$startTime, 1,19), format="%Y-%m-%dT%H:%M:%S")

curTime = with_tz(Sys.time(), "America/Chicago")
```


```{r plot}
# get hour breaks
hr_breaks_inds = (hour(hourly_forecast$startTime[1:48]) %% 6 == 0) & 
  !(hour(hourly_forecast$startTime[1:48]) %% 24 == 0)
hr_labs = hourly_forecast$startTime[1:48][hr_breaks_inds]
# shade nighttime
inds_night_start = hourly_forecast[2:48, "isDaytime"] == FALSE & hourly_forecast[1:47, "isDaytime"] == TRUE
inds_night_end = hourly_forecast[2:48, "isDaytime"] == FALSE & hourly_forecast[3:49, "isDaytime"] == TRUE
main_lab = paste0("Chicago, IL \nLast updated: ", curTime)

par(mar=c(5,5,3,1))
plot(hourly_forecast[1:48, c("startTime", "temperature")], 
     col="black", lwd=3, type="l", xlab="", ylab="Temp (F)", main=main_lab,
     cex.axis=1.5, cex.lab=1.5)
axis.POSIXct(1, at=hr_labs, format="%H", cex.axis=0.75)
rect(xleft = hourly_forecast[2:48, "startTime"][inds_night_start],
     xright = hourly_forecast[2:48, "startTime"][inds_night_end], 
     ybottom = par("usr")[3], ytop = par("usr")[4], 
     border = NA, col = adjustcolor("black", alpha = 0.3))
```

